DROP DATABASE IF EXISTS danclr;
CREATE DATABASE danclr;

\c danclr;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS followers;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR UNIQUE NOT NULL,
  email VARCHAR UNIQUE NOT NULL,
  password VARCHAR NOT NULL,
  Profile_Pic VARCHAR
);

CREATE TABLE post (
  id SERIAL PRIMARY KEY,
  user_id INT REFERENCES users(id) ON DELETE CASCADE,
  post_type VARCHAR,
  Post_Content VARCHAR NOT NULL,
  img_url VARCHAR,
  Time_Stamp Timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE likes (
  id SERIAL PRIMARY KEY,
  Post_Id INT REFERENCES post(id) ON DELETE CASCADE,
  LikedBy_Id INT REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE followers (
  id SERIAL PRIMARY KEY,
  FollowedBy_Id INT REFERENCES users(id) ON DELETE CASCADE,
  Following_Id INT REFERENCES users(id) ON DELETE CASCADE
);
